name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create release
        uses: release-drafter/release-drafter@v5
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 15
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '15'
          java-package: jdk
          cache: 'gradle'

      - name: Prepare google-services.json
        run: |
          echo '${{ secrets.GOOGLE_SERVICES }}' >> app/google-services.json
      - name: Prepare Gradle secure file
        run: |
          echo 'SIGNING_KEY_ALIAS=${{ secrets.SIGNING_KEY_ALIAS }}' >> local.properties
          echo 'SIGNING_KEY_PASSWORD=${{ secrets.SIGNING_KEY_PASSWORD }}' >> local.properties
      - name: Prepare Gradle version file
        run: |
          truncate -s 0 app/version.gradle
          echo "ext {" >> app/version.gradle
          echo "VERSION_NAME=\"${{ steps.create_release.outputs.tag_name }}\"" >> app/version.gradle
          echo "}" >> app/version.gradle
          cat app/version.gradle
      - name: Build APK
        id: build_apk
        run: |
          echo "Building ${{ steps.create_release.outputs.tag_name }}..."
          bash ./gradlew assembleRelease --stacktrace
      - name: APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: APK Artifact
          path: ./app/build/outputs/apk/release/app-release.apk

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ":robot: Commit Changes"
          file_pattern: "gradle.properties app/version.gradle"

      - name: Build AAB
        id: build_aab
        run: |
          echo "Building ${{ steps.create_release.outputs.tag_name }}..."
          bash ./gradlew bundleRelease --stacktrace
      - name: AAB Artifact
        id: aab_artifact
        uses: actions/upload-artifact@v3
        with:
          name: AAB Artifact
          path: ./app/build/outputs/bundle/release/app-release.aab

      - name: Prepare changelog
        id: prepare_changelog
        run: |
          mkdir -p -- "./changelog"
          # Insert the "more info url"
          echo "More info at: ${{ steps.create_release.outputs.html_url }}" > ./changelog/whatsnew-en-US
          echo "${{ steps.create_release.outputs.body }}" >> ./changelog/whatsnew-en-US
          # Remove all the markdown title double hashtag (##)
          sed -i 's/## //g' ./changelog/whatsnew-en-US
          # Remove the "Changes" title.
          sed -i 's/Changes//g' ./changelog/whatsnew-en-US
          # Remove markdown emojis
          sed -i 's/:.*: //g' ./changelog/whatsnew-en-US
          # Remove the author and issue id
          sed -i 's/ \@.*)//g' ./changelog/whatsnew-en-US
          truncate --size=499 ./changelog/whatsnew-en-US
          cat ./changelog/whatsnew-en-US
      - name: Upload to Play Store
        id: upload_play_store
        uses: r0adkll/upload-google-play@v1.0.17
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_GOOGLE_CLOUD_JSON }}
          packageName: com.arnyminerz.paraulogic
          releaseFiles: ./app/build/outputs/bundle/release/app-release.aab
          track: internal
          inAppUpdatePriority: 2
          # mappingFile: ./app/build/outputs/mapping/release/mapping.txt
          # whatsNewDirectory: ./changelog
          status: completed
